apiVersion: v1
description: Helm chart for hazelcast service in client server mode. Pega Infinity
  is a client and hazelcast service is a server.
home: http://www.pega.com
name: hazelcast
version: 1.0.0
