{{ $kindName := "" }}
{{ $apiVer := "" }}
{{ range $index, $dep := .Values.global.tier}}
{{ if ($dep.volumeClaimTemplate) }}
{{ $kindName = "StatefulSet" }}
{{ $apiVer = "apps/v1" }}
{{ else }}
{{ $kindName = "Deployment" }}
{{ $apiVer = "apps/v1" }}
{{ end }}

{{ $containerWaitList := list  }}
{{ if (eq (include "performOnlyDeployment" $) "true") }}
{{ if not $.Values.pegasearch.externalSearchService }}
{{ $containerWaitList = append $containerWaitList "waitForPegaSearch" }}
{{ end }}
{{ if (eq (include "cassandraEnabled" $) "true" ) }}
{{ $containerWaitList = append $containerWaitList "waitForCassandra" }}
{{ end }}
{{ end }}

{{ if (eq (include "performInstallAndDeployment" $) "true") }}
{{ $containerWaitList = append $containerWaitList "waitForPegaDBInstall" }} 
{{ if not $.Values.pegasearch.externalSearchService }}
{{ $containerWaitList = append $containerWaitList "waitForPegaSearch" }}
{{ end }}
{{ if (eq (include "cassandraEnabled" $) "true" ) }}
{{ $containerWaitList = append $containerWaitList "waitForCassandra" }}
{{ end }}
{{ end }}

{{ if (eq (include "performUpgradeAndDeployment" $) "true") }}
{{ $containerWaitList = append $containerWaitList "waitForPegaDBUpgrade" }}
{{ end }}

{{- if or (eq (include "performOnlyDeployment" $) "true") (eq (include "performInstallAndDeployment" $) "true") (eq (include "performUpgradeAndDeployment" $) "true") }}
{{ template "pega.deployment" dict "root" $ "node" $dep "name" (printf "pega-%s" $dep.name) "tierName" $dep.name "kind" $kindName "apiVersion" $apiVer "nodeType" $dep.nodeType "initContainers" $containerWaitList "custom" $dep.custom }}
{{- end }}
{{ end }}
