{{ if (eq (include "performDeployment" $) "true") }}
{{- if (eq .Values.global.provider "gke") }}
{{ range $index, $dep := .Values.global.tier }}
{{ if ($dep.ingress) }} 
{{ template "pega.gke.backendConfig" dict "root" $ "node" $dep "name" (printf "pega-%s" $dep.name) }}
{{ end }}
{{ end }}
{{ end }}
{{ end }}