{{ if (eq (include "performDeployment" .) "true") }}

{{ if (eq (include "isExternalSearch" .) "true") }}
# The deployment generates this file to deploy Elasticsearch internally when the external search URL is blank (or the default value is left) 
# AND no search service is enabled.
{{ else }}
kind: Service
apiVersion: v1
metadata:
  name: {{ template "searchName" . }}-transport
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "searchName" . }}
    component: Pega
spec:
  ports:
  - port: 80
    targetPort: 9300
    name: transport
  clusterIP: None
  selector:
    app: {{ template "searchName" . }}
    component: "Search"
{{ end }}
{{ end }}